### ISSUE TITLE
MVP Launch

### ISSUE THREAD

**Issue by atinux** [nuxt/nuxt.new#1]
Ives from CodeSandBox generously gave us `nuxt.new`, giving us the chance to improve the Nuxt creation workflow at the address bar level 🚀 

Figma: https://www.figma.com/file/dN1oInWdK9VifROnxPvoMw/Nuxt.new?node-id=2%3A12672

Landing page:

![Landing Page nuxt new](https://user-images.githubusercontent.com/904724/186675747-b2ec8f75-0606-480c-a2d9-32bbc21e684f.png)

Here are the following tasks for the MVP I imagine, but happy for you to handle it the way you seems best 😊 

- [x] Setup Nuxt 3 project
- [x] `data/starters.json` file with the list of branch of https://github.com/nuxt/starter
- [x] `data/themes.json` file with the list of themes from https://github.com/nuxt-themes (`alpine`, `docus`, `elements`)
- [x] Server route: `/c/:starter-or-theme` -> redirect 302 to its CodeSandBox url
- [x] Server route: `/s/:starter-or-theme` -> redirect 302 to its StackBlitz url
- [x] Server route: `/:theme` -> redirect 302 to its deployed version: `[theme].nuxt.dev/?studio` (used for the Edit button for projects using Studio)
- [x] `app.vue`
  - [x] List of the starters (title, description, nuxt logo) if starter or screenshot for theme) with a group button: Open on CodeSandbox | StackBlitz
  - [x] List of the themes (title, description, screenshot) with two button: Edit (with Nuxt logo) and a group button: Open on CodeSandbox | StackBlitz (hidden for the release)
